**Punto 1**

In [1]:
import numpy as np
import time

arr = np.array ([0,1,2,3,4,5,6,7,8,9])

print('')
print('si se tiene este arreglo '+ str(arr))

arr[1] = -1
arr[3] = -1
arr[5] = -1
arr[7] = -1
arr[9] = -1

print('')
print('se puede obtener este resultado'+ str(arr))



si se tiene este arreglo [0 1 2 3 4 5 6 7 8 9]

se puede obtener este resultado[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Punto 2**

In [2]:
import numpy as np
import time

a = np.arange(10)

print('si se tiene el arreglo '+ str(a))

a = np.arange(10).reshape(2,5)

print('')
print('se puede obtener este resultado ')
print('')
print(a)

si se tiene el arreglo [0 1 2 3 4 5 6 7 8 9]

se puede obtener este resultado 

[[0 1 2 3 4]
 [5 6 7 8 9]]


**Punto 3**

In [11]:
import numpy as np
import time

a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

print('se obtiene el resultado: ')
print('')
np.concatenate((a,b))

se obtiene el resultado: 



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Punto 4**

In [7]:
import numpy as np
import time

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)


array([2, 4])

**Punto 5**

In [8]:
import numpy as np
import time

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

a[:4]

array([1, 2, 3, 4])

**Punto 6**

In [82]:
import numpy as np
import time

a = np.array([2, 6, 1, 9, 10, 3, 27])

a[[1,3,4,]],


(array([ 6,  9, 10]),)

**Punto 7**

In [81]:
import numpy as np
import time

arr = np.arange(9).reshape(3,3)

arr [::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])